language: java

jdk:
  - oraclejdk8

script: mvn verify -B

env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "DzkJiTKFS05+Di2NSPFxBbpQON9ekyn9B1xnFrzeqHK1kUCQBpDk08afY24wETyDcTr4AgMyxLklv1iFXW083Pb+otzuuTIWfdPFKPw5LzRclVe/YXgpEonWfK3cI5nyDi7A5XOZu1LwKHXR/NDbJkKZHZRSo20B1RAz6L+j06E="

addons:
  coverity_scan:
    project:
      name: "davidmoten/rxjava-jdbc"
      description: "Reactive functional programming with JDBC"
    notification_email: davidmoten@gmail.com
    build_command_prepend: "mvn clean"
    build_command:   "mvn compile -DskipTests=true"
    branch_pattern: coverity_scan
